DROP TABLE IF EXISTS OUD21;
CREATE TABLE OUD21 AS 
SELECT 
  MAE.MBR_ID,
  DUAL_IND,
  ENROLLMENT
FROM 
  (SELECT 
    MBR_ID,
    MAX(CALENDAR_DATE) AS CALENDAR_DATE
   FROM 
    DATABOOK.MA_ENROLLMENT_V3 MAE
   WHERE
    CALENDAR_DATE BETWEEN '2021-01-01' AND '2021-12-31'
   GROUP BY 1) LATEST
JOIN 
  DATABOOK.MA_ENROLLMENT_V3 MAE
ON 
  (MAE.MBR_ID = LATEST.MBR_ID) AND (MAE.CALENDAR_DATE = LATEST.CALENDAR_DATE)
JOIN
  MISOWN.CLAIM_TRANS CT
ON 
  MAE.MBR_ID = CT.MBR_ID
JOIN
  MISOWN.CLAIM_DX DX
ON
  CT.CLAIM_TRANS_ID = DX.CLAIM_TRANS_ID
WHERE 
  CT.LATEST_TRANS_IND = 'Y' AND 
  DX.SRV_DT BETWEEN '2021-01-01' AND '2021-12-31' AND
  MAE.CALENDAR_DATE BETWEEN '2021-01-01' AND '2021-12-31' AND
  (LEFT(DX.DX_CD,4) = 'F111' OR LEFT(DX.DX_CD, 4) = 'F112');


---------------enrollment for oud statewide ----------------------------------------
SELECT 
dual_ind, enrollment,
COUNT(DISTINCT MBR_ID) FROM OUD21
group by 1,2;

---------------------------------Chronic Conditions for Statewide --------------------
SELECT
  BASE.DUAL_IND,
  BASE.ENROLLMENT,
  EDC.EDC_CD,
  REF.EDC_DESC,
  EDC.MDC_CD,
  REF.MDC_DESC,
  CASE 
    WHEN EDC.EDC_TYPE_CD = 'C' THEN 'Chronic'
    WHEN EDC.EDC_TYPE_CD = 'MC' THEN 'Major Chronic'
    WHEN EDC.EDC_TYPE_CD = 'DC' THEN 'Dominant Chronic'
    END AS EDC_TYPE ,
  COUNT(DISTINCT BASE.MBR_ID) AS N
FROM PROGOWN.MMM_MBR_EDC EDC
JOIN OUD21 BASE 
  ON EDC.MBR_ID = BASE.MBR_ID
LEFT JOIN PMQIDEV.REF_CRG_EDC_MDC REF
  ON EDC.EDC_CD = REF.EDC_CD AND
     REF.CRG_GRPR_VERSION = '2.10'
WHERE
  PER_END_DT = '2021-12-31' AND
  EDC_TYPE_CD IN ('C', 'DC', 'MC')
GROUP BY 1,2,3,4,5,6,7
ORDER BY 8 DESC;

----------------------------------Erie OUD Population ---------------------------
--8940 MEMBERS IN REPORT

DROP TABLE IF EXISTS HEAL_ERIE_OUD_2021;
CREATE TABLE HEAL_ERIE_OUD_2021 AS
SELECT
  DISTINCT(MBR_ID)
FROM
 HEAL_DENOM_MONTH HEAL
WHERE
  HEAL.MBR_RES_COUNTY = 'ERIE' AND 
  MONTH BETWEEN '2021-01-01' AND '2021-12-31'
  AND OUD_IND = 1;

SELECT * FROM HEAL_ERIE_OUD_2021;


---------------------------------Chronic Conditions for Erie --------------------
SELECT
  EDC.EDC_CD,
  REF.EDC_DESC,
  EDC.MDC_CD,
  REF.MDC_DESC,
  CASE 
    WHEN EDC.EDC_TYPE_CD = 'C' THEN 'Chronic'
    WHEN EDC.EDC_TYPE_CD = 'MC' THEN 'Major Chronic'
    WHEN EDC.EDC_TYPE_CD = 'DC' THEN 'Dominant Chronic'
    END AS EDC_TYPE ,
  COUNT(DISTINCT BASE.MBR_ID) AS N
FROM PROGOWN.MMM_MBR_EDC EDC
JOIN HEAL_ERIE_OUD_2021 BASE 
  ON EDC.MBR_ID = BASE.MBR_ID
LEFT JOIN PMQIDEV.REF_CRG_EDC_MDC REF
  ON EDC.EDC_CD = REF.EDC_CD AND
     REF.CRG_GRPR_VERSION = '2.10'
WHERE
  PER_END_DT = '2021-12-31' AND
  EDC_TYPE_CD IN ('C', 'DC', 'MC')
GROUP BY 1,2,3,4,5
ORDER BY 6 DESC;
